# Work flow control
RUN_ENKF=true
RUN_4DVAR=false
RUN_ENVAR=false
RUN_DETERMINISTIC=false
MULTI_PHYS_ENS=false
FOLLOW_STORM=false
CLEAN=false
INCLUDE_CHEM=true

# Experiment design
EXP_NAME=carbon
DATE_START=201507020000
DATE_END=201507061200
DATE_CYCLE_START=201507020600
DATE_CYCLE_END=201507060600

# Time control (in minutes)
CYCLE_PERIOD=360
WRFOUT_INTERVAL=(60)
LBC_INTERVAL=360
OBS_WIN_MIN=-180
OBS_WIN_MAX=180
MINUTES_PER_SLOT=60
FORECAST_MINUTES=360
WRFCHEMI_INTERVAL=60

# Directories
WORK_DIR=$WORK/playground/output_enkf/$EXP_NAME
SCRIPT_DIR=$WORK/playground/PSU_WRF_EnKF
CODE_DIR=$WORK/playground/WRF
DATA_DIR=$WORK/playground/data
WRF_DIR=$CODE_DIR/WRFV3.6.1_20tracers
WRF_BC_DIR=$SCRIPT_DIR/WRF_BC_v2.1_alltime/src
WRFDA_DIR=$CODE_DIR/WRFDAV3.6.1
WPS_DIR=$CODE_DIR/WPSV3.6.1
ENKF_DIR=$SCRIPT_DIR/EnKF/src
FG_DIR=$DATA_DIR/era-interim/2015
GEOG_DIR=$WORK/playground/data/geog_v3.6.1
BE_DIR=$WORK_DIR/be
EXTRAS_DIR=$DATA_DIR/extras
WRFCHEM_BC_DIR=$SCRIPT_DIR/wrfchem_bc
WRFCHEMI_DIR=$DATA_DIR/wrfchemi

# Domain setup
TWO_WAY_NESTING=false
MAX_DOM=1
E_WE=(250)
E_SN=(185)
E_VERT=(60)
DX=(27000)
DY=(27000)
TIME_STEP=30
PARENT_ID=(0)
GRID_RATIO=(1)
TIME_STEP_RATIO=(1)
I_PARENT_START=(1)
J_PARENT_START=(1)
MAP_PROJ="lambert" # mercator only now
REF_LAT=40.0
REF_LON=-96.0
STAND_LON=-96.0
TRUELAT1=30.0
TRUELAT2=60.0
P_TOP=5000

# Physics
MP_PHYSICS=(4)
RA_LW_PHYSICS=(1)
RA_SW_PHYSICS=(1)
RADT=(30)
SF_SFCLAY_PHYSICS=(5)
SF_SURFACE_PHYSICS=(2)
BL_PBL_PHYSICS=(5)
BLDT=(0)
CU_PHYSICS=(1)
CUDT=(0)
SST_UPDATE=1

# EnKF options
NUM_ENS=5
NMCPU=$((NUM_ENS+1))
NICPU=1
NJCPU=1
INFLATION_COEF=1.0
RELAX_OPT=0
RELAX_ADAPTIVE=false
RELAXATION_COEF=0.8
REPLACE_MEAN=false
REPLACE_MEAN_WITH=forecast

# Data sources
INCLUDE_LITTLE_R=false
INCLUDE_BUFR=false
INCLUDE_MADIS=true
USE_SYNOPOBS=false
USE_SURFOBS=false
USE_SOUNDOBS=true
USE_PILOTOBS=false
USE_PROFILEROBS=false
USE_AIREPOBS=false
USE_METAROBS=false
USE_SHIPSOBS=false
USE_SSMIOBS=false
USE_SATEMOBS=false
USE_GPSPWOBS=false
USE_GPSREFOBS=false
USE_ATOVS=false
USE_GEOAMVOBS=false
USE_POLARAMVOBS=false
USE_QSCATOBS=false
USE_RADAROBS=false
USE_RADAR_RF=false
USE_RADAR_RV=false
USE_AIRBORNE_RF=false
USE_AIRBORNE_RV=false
USE_BOGUSOBS=false
USE_BUOYOBS=false

# Data thinning coef for EnKF
THIN_SURFACE=10
THIN_SOUNDING=10
THIN_PROFILER=5
THIN_AIRCFT=10
THIN_METAR=10
THIN_SFCSHP=5
THIN_SPSSMI=10
THIN_ATOVS=10
THIN_SATWND=20
THIN_GPSPW=0
THIN_RADAR=5

# Localization distance for EnKF (km for HROI, number of layers for VROI)
HROI_SFC=1200
HROI_UPPER=1200
HROI_RADAR=45 #with SCL option
VROI=15
VROI_RADAR=15

# WRFDA options (for generating perturbations)
CV_OPTIONS=3
VAR_SCALING1=1.0
VAR_SCALING2=1.0
VAR_SCALING3=1.0
VAR_SCALING4=1.0
VAR_SCALING5=1.0
LEN_SCALING1=1.0
LEN_SCALING2=1.0
LEN_SCALING3=1.0
LEN_SCALING4=1.0
LEN_SCALING5=1.0

# CPU usage
HOSTPPN=16
HOSTTYPE=stampede
JOB_SUBMIT_MODE=1
wrf_ntasks=32
real_ntasks=32
var3d_ntasks=$HOSTPPN
var4d_ntasks=$HOSTPPN
var4d_ppn=4
enkf_ntasks=$((NMCPU*$NICPU*$NJCPU))
enkf_ppn=4

# WRF-CHEM options
NTRACER=20
TRACER_BC=(2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2) # 1 = CT, 2 = 300, 3 = 0
